typography_spectrum: 0.4179285957943648
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#9b7f53'
    - '#472b18'
    - '#044582'
  brandStrength: 0.5
  lightness: 0.34139297623187304
  saturation: 0.2365440872963518
  rhythmicContrast: 0.941647850908339
opengraph:
  image: null
  type: Testing in FB
  appId: null
layout_spectrum: 0.5903
analytics:
  google: null
  facebook: null
  twitter: null
name: Starshine
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Theta Healing GR
purpose: []
